server:
  port: 8090
spring:
  profiles:
    active: dev
  datasource:
      url : jdbc:mysql://localhost:3306/chan
      username : root
      password : 123456
      driverClassName : com.mysql.jdbc.Driver

